# Generated by Django 5.1.6 on 2025-04-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_month_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_week_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
